name: Sample github work flow

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  django_test:
    runs-on: ubuntu-latest

    env:
      DJANGO_SECRETS: "this is secret code"
  
    steps:
      - name: Checkout django test
        uses: actions/checkout@v2
      - name: Setup Python 3.10
        uses: actions/checkout@v2
        with:
          python-version: "3.10"
      - name: Install requirements
        run: |
          python -m pip install pip --upgrade
          python -m pip install -r requirements.txt
      - name: Run test
        run: |
          echo "Running test for Django project"
          echo ${{ env.DJANGO_SECRETS }}